# 
#  EpicGlass v1.22
#  
#  For help with your config file, please see the BukkitDev page 
#  
Shield:
  CheckBuildPermission: true
WorldsEnabled:
  world: true
  world_nether: true
  world_the_end: true
BlocksAffectedByBreaks:
  Signs: false
  Torches: false
  Vines: false
  Water: true
  Lava: true
Damage:
  Sprinting: 1.5
  Falling: -4
BreakableBlocks:
  GLASS:
    Types:
      All:
        BreakType:
          Hitting:
            Player:
              Enabled: true
              HitsTaken: 1
              ItemsEnabled:
              - STONE_TOOLS
          Falling:
            Player: true
            Mob: true
          Sprinting:
            Player: true
          Projectile:
            Arrow:
              Player: true
              Mob: true
              Dispenser: true
            Guns+: true
        SetType:
          Material: AIR
          DataValue: 0
        Ranges:
          MinimumFallDistance: 5
          MaxBlocksBroken: 0
        Regeneration:
          Enabled: true
          Chance: 15
          TimeBeforeRegenStarts: 60
        AssociatedBlocks:
        - NONE
        DropsBlocks: false
